#!/bin/bash

[ -v _MODULE_LAUREL_KERNEL_ ] &&
    return 0 || _MODULE_LAUREL_KERNEL_=

laurel::handle() {
    local tmp="$1"
    shift

    laurel::commands.${tmp//:/ } "$*"
}

laurel::commands.make() {
    local file_type="$1"
    shift

    file_path="$__laurel_DIR__/lib/laurel/templates/$file_type"
    [ -f $file_path ] || return 1

    case $file_type in
    test)
        cat $file_path >"$__laurel_DIR__/tests/$1"
        echo $?
        ;;
    esac
}

laurel::commands.test() {
    case $1 in
    run)
        for script in $(find $__laurel_DIR__/tests -type f); do
            chmod +x $script
            echo testing file ${script##$__laurel_DIR__}:
            echo

            $script

            echo
        done
        ;;
    esac
}
